version: '3.8'

services:
  web:
    build: .
    restart: always
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env

  redis:  
    image : "redis:alpine"
    restart: always

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"

  celery:
    build: .
    restart: always
    command: poetry run celery -A core worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    restart: always
    command: poetry run celery -A core beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - beat_schedule:/celery-beat-schedule

volumes:
 static_volume:
 media_volume:
 beat_schedule: