# Generated by Django 5.0.4 on 2024-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyrates',
            index=models.Index(fields=['-date'], name='currency_cu_date_60df4a_idx'),
        ),
    ]
