# Generated by Django 5.0.4 on 2024-07-12 16:50

import api.trip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_trip_trip_date_a8ddb9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='trip_images/default/default_trip_image.png', upload_to=api.trip.models._user_directory_path),
        ),
    ]
