# Generated by Django 5.0.4 on 2024-10-14 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_image_alter_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
        migrations.AddField(
            model_name='trip',
            name='image_id',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
