# Generated by Django 5.0.4 on 2024-10-14 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_trip_image_trip_image_id_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
