# Generated by Django 5.0.4 on 2024-07-07 15:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Accomodation'), (1, 'Food'), (2, 'Health'), (3, 'Transport'), (4, 'Activities'), (5, 'Others')])),
                ('data', models.DateField(default=datetime.date(2024, 7, 7))),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trip.trip')),
            ],
        ),
    ]
