# Generated by Django 5.0.4 on 2024-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_options_remove_expense_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Activities'), (1, 'Accomodation'), (2, 'Food'), (3, 'Health'), (4, 'Shopping'), (5, 'Transport'), (6, 'Souvenirs'), (7, 'Others')]),
        ),
    ]
