# Generated by Django 5.0.4 on 2024-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
